
train:
  - [ './data/ECB.trn.en.gz',  './data/ECB.trn.fr.gz'  ]
  - [ './data/EMEA.trn.en.gz', './data/EMEA.trn.fr.gz' ]
  - [ './data/KDE4.trn.en.gz', './data/KDE4.trn.fr.gz' ]
  - [ './data/ECB.trn.en.gz'  ]
  - [ './data/EMEA.trn.en.gz' ]
  - [ './data/KDE4.trn.en.gz' ]
max_length: 160
batch_size: [32, 4]
train_steps: 1000000
msk_step: { every: 3, prob: 0.15, same: 0.1, rand: 0.1 }
#sim_step: { every: 3, parallel: 0.5 }
#ali_step: { every: 3, parallel: 0.5 }
checkpoint_every_steps: 1000
validation_every_steps: 5000
report_every_steps: 100
average_last_n: 10

